### ISSUE TITLE
Remove .Rproj.user from repo

### ISSUE THREAD

**Issue by walkerjeffd** [Conte-Ecology/conteStreamTemperature#1]
Looks like you added the .Rproj.user folder to the git repo before creating the .gitignore file.  This might cause problems for others who clone the repo and open it in RStudio. 

I _think_ you can remove it by running this at command line:

```
git rm -r --cached .Rproj.user
```

Note you may want to just move this out of your local directory temporarily (and then put it back in after running git rm) because this might not only remove it from the repo but delete the folder also (but I think the --cached flag is supposed to prevent that). But just to be safe, keep a backup copy in another directory in case it does delete it.

**Comment by ghost** [comment]
This worked well for me, thanks!
