### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by djhocking** [Conte-Ecology/conteStreamTemperature#26]
```
==> devtools::document(roclets=c('rd', 'collate', 'namespace'))

Updating conteStreamTemperature documentation
Loading conteStreamTemperature
Error in parse(text = lines, n = -1, srcfile = srcfile) : 
  /Users/Dan/Documents/Research/Stream_Climate_Change/conteStreamTemperature/R/predictionFunctions.R:590:0: unexpected end of input
588:   return(derivedfeatureidMetrics)
589: }
    ^
Calls: suppressPackageStartupMessages ... in_dir -> force -> source_many -> source_one -> parse
Execution halted

Exited with status 1.
```

I don't think the error is at the `return() }` stage. That looks okay. I think it has to do with `Error in parse(text = lines, n = -1, srcfile = srcfile) : `. I am not sure what that refers to but I think it might be the `fetch` from the database using the `RPostgreSQL` package. It could be a problem building a package that calls to the database. I have no idea. The code seems to work fine when I load the functions locally.

**Comment by walkerjeffd** [comment]
I tracked down the bug. You're missing an ending "}" for `calcYearsMaxTemp()`. I think the return statement might be within the wrong {} block also. I tried sourcing the functions one by one, and that one didn't have a ending bracket.

**Comment by djhocking** [comment]
Thanks. I guess I messed that up when I merged the two versions of the function. I didn't realize I had merged them after the last test. That's the problem with bouncing between 3 computers in a sleep-deprived state. I fixed it, rebuilt, and pushed. It should work now (fingers crossed).
