### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by youngday2** [Conte-Ecology/conteStreamTemperature#38]
I got the following error when installing

> install_github("conteStreamTemperature", username = "Conte-Ecology")
Error in parse_repo_spec(repo) : 
  Invalid git repo specification: 'conteStreamTemperature'
Warning message:
1 components of `...` were not used.
We detected these problematic arguments:
* `username`

Solution for me was this

install_github("Conte-Ecology/conteStreamTemperature")

**Comment by djhocking** [comment]
Thanks. devtools/remotes changed their syntax. I've fixed the readme per your solution.
